apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-service-deploy
  labels:
    name: grpc-pod-demo
    app: demo-grpc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grpc-pod-demo
      app: demo-grpc-app
  template:
    metadata:
      name: grpc-app-pod
      labels:
        name: grpc-pod-demo
        app: demo-grpc-app
    spec:
      containers:
      - name: grpc-server
        image: paras1008/grpc_project_images:grpc-server
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: grpc-server
